### ISSUE TITLE
Try 'pymobiledevice3 developer dvt simulate-location set -h' for help.  Error: Invalid value for '--rsd': '' is not a valid integer.

### ISSUE THREAD

**Issue by yanye666** [RManLuo/FakePosition#2]
Try 'pymobiledevice3 developer dvt simulate-location set -h' for help.

Error: Invalid value for '--rsd': '' is not a valid integer.

**Comment by yanye666** [comment]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/__main__.py", line 125, in <module>
    cli()
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/__main__.py", line 77, in cli
    cli_commands()
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/cli/cli_common.py", line 101, in wrapper
    func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/cli/remote.py", line 159, in cli_start_quic_tunnel
    asyncio.run(tunnel_task(rsd, secrets, script_mode, max_idle_timeout=max_idle_timeout), debug=True)
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/cli/remote.py", line 97, in tunnel_task
    async with start_quic_tunnel(service_provider, secrets=secrets, max_idle_timeout=max_idle_timeout) as tunnel_result:
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 591, in start_quic_tunnel
    with create_core_device_tunnel_service(service_provider, autopair=True) as service:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 581, in create_core_device_tunnel_service
    service.connect(autopair=autopair)
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 212, in connect
    if not self._validate_pairing():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 453, in _validate_pairing
    peer_public_key = X25519PublicKey.from_public_bytes(data[PairingDataComponentType.PUBLIC_KEY])
                                                        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: EnumIntegerString.new(3, 'PUBLIC_KEY')

**Comment by RManLuo** [comment]
Have you tried to run it with `sudo` ?

**Comment by yanye666** [comment]
sudo sh /Users/yanlun/Downloads/change_ios_position.sh -27.32112 153.06814

**Comment by yanye666** [comment]
我是执行这个命令，我看sh脚本是，是变量读取失败，底层还是执行nohup sudo python3 -u -m pymobiledevice3 remote start-quic-tunnel，这个错误就是这个命令的

**Comment by yanye666** [comment]
![image](https://github.com/RManLuo/FakePosition/assets/42414099/9452471f-61bd-4983-8ed3-1dc6758fa574)

**Comment by RManLuo** [comment]
I think I also faced a similar problem before. I think it could be related to the packages of the SSL lib. 

If I remember correctly, it can be fixed by updating some python SSL packages. But, I cannot recall their names.

**Comment by yanye666** [comment]
😭😭😭😭

**Comment by Yourzean** [comment]
Update the libressl to openssl
Use the following command(install homebrew first)
`brew install openssl`
Put `export PATH="/opt/homebrew/opt/openssl@x.x/bin:$PATH"` in `~/.zshrc`
Type `openssl -v` to check ssl version.
The expected response is `OpenSSL x.x.x `, not `LibreSSL x.x.x`

**Comment by yanye666** [comment]
> Update the libressl to openssl Use the following command(install homebrew first) `brew install openssl` Put `export PATH="/opt/homebrew/opt/openssl@x.x/bin:$PATH"` in `~/.zshrc` Type `openssl -v` to check ssl version. The expected response is `OpenSSL x.x.x `, not `LibreSSL x.x.x`

openssl version
LibreSSL 3.3.6

**Comment by RManLuo** [comment]
https://github.com/doronz88/pymobiledevice3/commit/c42f2ebf5522a3647fd52725516c1736af916640
